---

env:
  global:
    - CC_TEST_REPORTER_ID=50dddec66a9d6476df64b3aaa10f5b094f38e264f91db74d7d247e973cc9dcd6

language: node_js
node_js:
  - node

before_script:
  - npm install codeclimate-test-reporter -g

script: 
  - make lint
  - make test-coverage

after_script:
  - codeclimate-test-reporter <./coverage/lcov.info